export interface IGithubRepos {
    name: string;
    topics: [];
    html_url: string;
    description: string;
    id: number;
    homepage: string;
}
export declare function useGithubAutomatedRepos(): {
    dataReposGithub: (data: [], keyWordDeploy: string) => {
        id: number;
        name: string;
        html_url: string;
        description: string;
        topics: [];
        homepage: string;
    }[];
};
export declare function IconsData(): {
    iconStacks: {
        androidstudio: string;
        angular: string;
        arduino: string;
        aws: string;
        bootstrap: string;
        c: string;
        clion: string;
        cpp: string;
        csharp: string;
        css3: string;
        dart: string;
        django: string;
        docker: string;
        eclipse: string;
        eslint: string;
        expo: string;
        express: string;
        figma: string;
        firebase: string;
        flask: string;
        gatsby: string;
        git: string;
        go: string;
        html5: string;
        husky: string;
        java: string;
        javascript: string;
        jest: string;
        kotlin: string;
        laravel: string;
        linux: string;
        lua: string;
        mongodb: string;
        mysql: string;
        netcore: string;
        nextjs: string;
        nodejs: string;
        npm: string;
        objectc: string;
        pearl: string;
        php: string;
        postgresql: string;
        prettier: string;
        prisma: string;
        python: string;
        rails: string;
        react: string;
        reacticons: string;
        ruby: string;
        rust: string;
        sass: string;
        scala: string;
        spring: string;
        sqlite: string;
        storybook: string;
        styledcomponents: string;
        swagger: string;
        switch: string;
        tailwind: string;
        typescript: string;
        visualstudio: string;
        visualstudiocode: string;
        vitejs: string;
        vue: string;
    };
    iconsProjects: {
        api: string;
        art: string;
        artificialintelligence: string;
        dashboard: string;
        education: string;
        eletronic: string;
        game: string;
        landingpage: string;
        personalwebsite: string;
        productivity: string;
        security: string;
        store: string;
        weather: string;
    };
};
