name: Bug Report
description: Report a bug in the github-automated-repos

body:
  - type: dropdown
    id: affected-elements
    attributes:
      label: Which element(s) are the source of the bug?
      options:
        - useGithubAutomatedRepos (Hook)
        - stackIcons (Component)
        - stackLabels (Component)
        - banner (Props)
        - icons (stack IMGs)
        - docs
        - Don't known / other
      multiple: true
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
    validations:
      required: true

  - type: input
    id: reproduction
    attributes:
      label: Please provide a link to a minimal reproduction of the bug     

  - type: textarea
    id: exception-or-error
    attributes:
      label: Please provide the exception or error you saw
      render: true

  - type: textarea
    id: other
    attributes:
      label: Anything else?

  - type: markdown
    attributes:
      value: "Thank you so much for contributing to an ever-better lib!"
