## for more information about YAML Syntax
#https://docs.github.com/pt/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-githubs-form-schema

name: "Feature Request"
description: Missing a Project or Stack icon? Or any API props? Any other suggestion? Tell us which one is missing.

body:
  - type: dropdown
    id: feature-type
    attributes:
      label: Which category is it related to?
      options:
        - useGithubAutomatedRepos (Hook)
        - stackIcons (Component)
        - stackLabels (Component)
        - banner (Props)
        - icons (stack IMGs)
        - docs
        - Othes
      multiple: true
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describes what is missing. Example -
      placeholder: |
        - Ex.:
        - New Stack Icon: javascript, reactjs...                                                                
        - New Feature: describe...
        - homepage: props for access the link project.
    validations:
      required: true


  - type: textarea
     id: proposed-solution
     attributes:
      label: Proposed solution
   validations:
      required: true

    - type: textarea
    id: alternatives-considered
    attributes:
      label: Alternatives considered
    validations:
      required: false

  - type: markdown
    attributes:
      value: "Thank you so much for contributing to an ever-better lib!"
